import fs from 'node:fs';import path from 'node:path';
import {ROOT,read,write,hash,inside,mkdir} from '../lib/io.mjs';
export function pack(target){target=path.resolve(target);if(inside(ROOT,target)||fs.existsSync(target))throw new Error('Use a new directory outside skill');mkdir(target);
 const files=['SKILL.md','README.md','VALIDATION.md','LICENSE','THIRD_PARTY_NOTICES.md','package.json','package-lock.json','requirements-skia.txt','agents/openai.yaml','.claude-plugin/plugin.json'];
 const scripts=['motion.mjs','setup.mjs','install.mjs','connect-presentation.mjs','pack.mjs','glyphs.py','rhythm_features.py','rhythm_refine.py','music_structure.py','audio_clock_audit.py','skia_frames.py','create-demo.mjs','music-audit.mjs','test.mjs'];
 const refs=['subject-understanding.md','preproduction.md','cli.md','contract.md','directing.md','show-the-subject.md','longform.md','quality.md','visual-acceptance.md','image-art.md','material-flow.md','brand-direction.md','engine-selection.md','production-methods.md','spatial.md','audio-edit.md','automotive-review.md','precision-driving.md','music-direction.md','event-ending.md','routes.md','hybrid-production.md','editorial-review.md','word-sync.md','rhythm-direction.md','musical-structure.md'];
 for(const folder of ['lib','assets','contracts','vendor','examples-public','tests-public']){
  const source=path.join(ROOT,fs.existsSync(path.join(ROOT,folder))?folder:folder.replace('-public','')),name={'examples-public':'examples','tests-public':'tests'}[folder]||folder;if(!fs.existsSync(source))throw new Error('Missing public component '+folder);
  fs.cpSync(source,path.join(target,name),{recursive:true,filter:f=>!/(?:^|[/\\])(?:\.git|node_modules|__pycache__|provenance\.json)(?:[/\\]|$)/.test(f)});
 }
 for(const f of files.concat(scripts.map(x=>'scripts/'+x),refs.map(x=>'references/'+x))){const dest=path.join(target,f);mkdir(path.dirname(dest));fs.copyFileSync(path.join(ROOT,f),dest);}
 const assets=path.join(target,'assets/art');if(fs.existsSync(assets)){write(path.join(assets,'provenance.json'),{origin:'OpenAI native image generation',scope:'Authored material artwork for this package',assets:fs.readdirSync(assets).filter(x=>x.endsWith('.png')).map(n=>({file:n,sha256:hash(fs.readFileSync(path.join(assets,n)))})),prompts:'Individual example project asset records contain author prompts. Local session IDs omitted.'});}
 const inventory=[];function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,item.name);if(item.isDirectory())walk(f);else{const rel=path.relative(target,f).replaceAll('\\','/'),bytes=fs.readFileSync(f);if(!rel.startsWith('vendor/')&&/\.(?:json|md|mjs|js|py|txt|yaml)$/.test(rel)&&/(?:C:[/\\]+Users[/\\]|C:[/\\]+CodexHome|native-session:[a-f0-9-]{36}|work-[a-f0-9]{32})/i.test(bytes.toString('utf8')))throw new Error('Private path/session in '+rel);inventory.push({path:rel,bytes:bytes.length,sha256:hash(bytes)});}}}walk(target);write(path.join(target,'package-manifest.json'),{version:'3.0.0-rc.1',files:inventory});return {directory:target,files:inventory.length,bytes:inventory.reduce((n,f)=>n+f.bytes,0)};
}
if(process.argv[1]&&path.resolve(process.argv[1])===path.join(ROOT,'scripts/pack.mjs'))console.log(JSON.stringify(pack(process.argv[2])));
