import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {pathToFileURL} from 'node:url';
import {playwright,ROOT,inside} from './io.mjs';
export const CPU_ARGS=['--disable-gpu','--disable-gpu-compositing','--disable-accelerated-2d-canvas','--disable-accelerated-video-decode','--disable-accelerated-video-encode','--disable-webgl','--force-color-profile=srgb'];
export const SPATIAL_CPU_ARGS=['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-gpu-compositing','--disable-accelerated-video-decode','--disable-accelerated-video-encode','--force-color-profile=srgb'];
export async function browser(p){const pw=await playwright();return pw.chromium.launch({headless:true,args:p?.renderer==='spatial-three'?SPATIAL_CPU_ARGS:CPU_ARGS});}
export async function pageFor(b,file,width,height){
 const context=await b.newContext({viewport:{width,height},deviceScaleFactor:1});const denied=[],errors=[];
 // Read inline renderer documents with Node (Windows long-path aware). The exact
 // intercepted URL performs no network request; all other network access stays denied.
 const documentUrl='http://motion-render.invalid/document.html',body=fs.readFileSync(file);
 await context.route('**/*',route=>{const u=route.request().url();if(u===documentUrl)return route.fulfill({status:200,contentType:'text/html; charset=utf-8',body});if(/^(file:|data:|about:)/.test(u))return route.continue();denied.push(u);return route.abort();});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(documentUrl);try{await page.waitForFunction(()=>window.__ready===true||window.__engineError);const failure=await page.evaluate(()=>window.__engineError);if(failure)throw Error(failure);}catch(e){await context.close();throw Error(e.message+' '+errors.join('; '));}return {page,context,denied,errors};
}
export function serve(dir,port=0){dir=fs.realpathSync(dir);return new Promise((resolve,reject)=>{const server=http.createServer((req,res)=>{let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);}catch{res.writeHead(400).end();return;}const file=path.resolve(dir,'.'+pathname+(pathname.endsWith('/')?'index.html':''));if(!inside(dir,file)||!fs.existsSync(file)||!inside(dir,fs.realpathSync(file))||!fs.statSync(file).isFile()){res.writeHead(404).end();return;}const size=fs.statSync(file).size,types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.svg':'image/svg+xml','.mp4':'video/mp4','.wav':'audio/wav','.png':'image/png','.woff2':'font/woff2','.css':'text/css'},headers={'Content-Type':types[path.extname(file)]||'application/octet-stream','Accept-Ranges':'bytes'};let start=0,end=size-1,code=200;if(req.headers.range){const match=/^bytes=(\d*)-(\d*)$/.exec(req.headers.range);if(!match||(!match[1]&&!match[2])||!size){res.writeHead(416,{'Content-Range':'bytes */'+size}).end();return;}if(!match[1])start=Math.max(0,size-Number(match[2]));else start=Number(match[1]);if(match[1]&&match[2])end=Math.min(end,Number(match[2]));if(start>end||start>=size){res.writeHead(416,{'Content-Range':'bytes */'+size}).end();return;}code=206;headers['Content-Range']='bytes '+start+'-'+end+'/'+size;}headers['Content-Length']=Math.max(0,end-start+1);res.writeHead(code,headers);if(req.method==='HEAD'||size===0){res.end();return;}fs.createReadStream(file,{start,end}).pipe(res);});server.on('error',reject);server.listen(port,'127.0.0.1',()=>resolve({server,url:'http://127.0.0.1:'+server.address().port}));});}
