// Descriptive editorial evidence, never a score for aesthetic quality.
const list=x=>Array.isArray(x)?x:[];
const rounded=x=>Math.round(x*1000)/1000;
const overlap=(a,b,c,d)=>Math.max(0,Math.min(b,d)-Math.max(a,c));
const median=a=>{const b=[...a].sort((x,y)=>x-y),i=Math.floor(b.length/2);return b.length?(b.length%2?b[i]:(b[i-1]+b[i])/2):0;};
function union(intervals){let n=0,end=-Infinity;for(const [a,b]of [...intervals].sort((u,v)=>u[0]-v[0])){n+=Math.max(0,b-Math.max(a,end));end=Math.max(end,b);}return n;}
export function pacingInventory(p,{windowSeconds=15}={}){
 const fps=p.output?.fps,total=p.output?.total_frames,scenes=list(p.scenes);
 if(!Number.isFinite(fps)||fps<=0||!Number.isInteger(total)||total<=0||!Number.isFinite(windowSeconds)||windowSeconds<.5||windowSeconds>120)throw Error('pacing review requires finite project frames/fps and 0.5..120 second windows');
 if(!scenes.length||scenes.some((s,i)=>!Number.isInteger(s.start)||!Number.isInteger(s.end)||s.end<=s.start||s.start!==(i?scenes[i-1].end:0))||scenes.at(-1).end!==total)throw Error('pacing review requires ordered contiguous full-project shots');
 const duration=total/fps,bindings=list(p.rhythm_score?.bindings),events=list(p.rhythm_score?.events),assets=new Map(list(p.assets).map(a=>[a.asset_id,a]));
 const identity=id=>assets.get(id)?.sha256||id;
 const shots=scenes.map(s=>({id:s.id,start:rounded(s.start/fps),end:rounded(s.end/fps),seconds:rounded((s.end-s.start)/fps),rawStart:s.start/fps,rawEnd:s.end/fps,sourceKeys:list(s.composition?.layers).filter(l=>l.kind==='video').map(l=>identity(l.asset_id)),cutBound:bindings.some(b=>b.scene_id===s.id&&b.target?.kind==='cut'),transition:s.transition_in?.type||s.transition_in?.kind||null}));
 const lengths=scenes.map(s=>(s.end-s.start)/fps),bins=[[0,1],[1,2],[2,4],[4,8],[8,Infinity]].map(([a,b])=>{const v=lengths.filter(x=>x>=a&&x<b);return {seconds:[a,Number.isFinite(b)?b:null],shots:v.length,screenSeconds:rounded(v.reduce((n,x)=>n+x,0)),screenShare:rounded(v.reduce((n,x)=>n+x,0)/duration)};});
 const windows=[];
 for(let start=0;start<duration;start+=windowSeconds){const end=Math.min(duration,start+windowSeconds),active=shots.filter(s=>s.rawStart<end&&s.rawEnd>start),cuts=shots.filter(s=>s.rawStart>0&&s.rawStart>=start&&s.rawStart<end);windows.push({start:rounded(start),end:rounded(end),shotStarts:cuts.length,explicitMusicCutBindings:cuts.filter(s=>s.cutBound).length,activeShots:active.map(s=>s.id),uniqueVideoSources:new Set(active.flatMap(s=>s.sourceKeys)).size,secondsInShotsAtLeastFourSeconds:rounded(active.filter(s=>s.rawEnd-s.rawStart>=4).reduce((n,s)=>n+overlap(start,end,s.rawStart,s.rawEnd),0))});}
 const sources=new Map();
 for(const s of scenes)for(const l of list(s.composition?.layers).filter(l=>l.kind==='video')){const key=identity(l.asset_id),speed=l.speed??1;if(!Number.isFinite(l.source_in)||!Number.isFinite(speed)||speed<=0)throw Error('pacing review requires valid video source clocks');const entry=sources.get(key)||{key,assetIds:[],shots:[],ranges:[],outputSeconds:0};if(!entry.assetIds.includes(l.asset_id))entry.assetIds.push(l.asset_id);entry.shots.push(s.id);entry.ranges.push([l.source_in,l.source_in+(s.end-s.start)/fps*speed]);entry.outputSeconds+=(s.end-s.start)/fps;sources.set(key,entry);}
 const holds=list(p.rhythm_score?.holds).map(h=>[h.start_frame/fps,h.end_frame/fps]).filter(([a,b])=>Number.isFinite(a)&&Number.isFinite(b)&&a>=0&&b>a&&b<=duration);
 const by=(items,key)=>Object.fromEntries([...new Set(items.map(key))].map(k=>[k,items.filter(x=>key(x)===k).length]));
 return {version:'pacing-inventory-v1',project:p.project_id,durationSeconds:rounded(duration),shotCount:shots.length,cutCount:Math.max(0,shots.length-1),meanShotSeconds:rounded(duration/shots.length),medianShotSeconds:rounded(median(lengths)),maxShotSeconds:rounded(Math.max(...lengths)),durationBins:bins,protectedSingleShotSeconds:rounded(union(holds)),eventMethods:by(events,e=>e.method||'unrecorded'),bindingsByTarget:by(bindings,b=>b.target?.kind||'unknown'),explicitCutBindingCount:shots.filter(s=>s.cutBound&&s.rawStart>0).length,videoSources:[...sources.values()].map(v=>({key:v.key,assetIds:v.assetIds,shotIds:v.shots,outputSeconds:rounded(v.outputSeconds),selectedSourceSeconds:rounded(v.ranges.reduce((n,[a,b])=>n+b-a,0)),uniqueSourceSeconds:rounded(union(v.ranges))})),windows,shots:shots.map(({rawStart,rawEnd,...s})=>s),limitations:['Shot count is not visual variety: splitting one image or changing copy cannot establish new coverage.','An absent explicit cut binding does not prove a cut is off beat; a binding does not prove an audible onset.','Duration bins describe this edit, not universal minimum/maximum shot lengths.','Source identity and repeated intervals do not measure composition, camera continuity or meaning.'],qualityDecision:'not assessed: inspect actual sequence flow and heard musical phrasing',listeningDecision:'not assessed'};
}
