export function spatialErrors(p){
 if(p.schema_version==='3.1.0')p={...p,renderer:'spatial-three',scenes:(p.scenes||[]).filter(s=>(s.renderer||p.renderer)==='spatial-three')};
 if(!p.scenes?.length)return [];
 try{return spatialErrorsUnsafe(p).concat(precisionErrors(p));}catch{return ['spatial: malformed nested geometry, camera or plate data'];}
}
function precisionErrors(p){
 if(p.renderer!=='spatial-three'||p.spatial?.version!=='precision-1')return [];
 const e=[],ok=(v,m)=>{if(!v)e.push('precision: '+m);},vec=v=>Array.isArray(v)&&v.length===3&&v.every(Number.isFinite),ids=new Set(p.spatial.nodes.map(n=>n.id));
 const textures=p.spatial.textures||{};
 for(const d of Object.values(textures)){ok(typeof d.svg==='string'&&d.svg.length<1500000&&!/<(?:script|image|feImage|foreignObject|iframe|style)\b|\bon\w+\s*=|(?:href|src)\s*=\s*["'](?!#)|url\(\s*["']?(?!#)/i.test(d.svg),'unsafe vector texture');ok(Number.isInteger(d.width)&&Number.isInteger(d.height)&&d.width>0&&d.height>0&&d.width<=2048&&d.height<=2048,'texture budget');}
 for(const n of p.spatial.nodes){if(n.material?.texture)ok(!!textures[n.material.texture],'missing vector texture');if(n.geometry?.uv)ok(Array.isArray(n.geometry.uv)&&n.geometry.uv.length===n.geometry.vertices.length/3*2&&n.geometry.uv.every(Number.isFinite),'mesh UV count');}
 for(const s of p.scenes){const c=s.spatial;if(c.plates?.length)ok(false,'precision renderer uses geometry, not photo plates');if(c.camera.relative_to)ok(ids.has(c.camera.relative_to),'relative camera target missing');
  for(const [id,q]of Object.entries(c.transforms||{})){ok(ids.has(id),'transform target missing');let last=-1;for(const k of [{at:0,...q},...(q.keyframes||[])]){ok(Number.isFinite(k.at)&&k.at>=last&&k.at<=(s.end-s.start)/30,'transform time');last=k.at;for(const name of ['position','rotation','scale'])ok(k[name]===undefined||vec(k[name]),'transform vector');}}
  if(s.spatial_transition)ok(['shutter'].includes(s.spatial_transition.kind)&&Number.isFinite(s.spatial_transition.duration)&&s.spatial_transition.duration>0&&s.spatial_transition.duration<=.6,'only shutter spatial transitions are implemented (0 < duration <= 0.6)');
 }
 return e;
}
function spatialErrorsUnsafe(p){
 if(p.renderer!=='spatial-three')return [];const errors=[],ok=(v,m)=>{if(!v)errors.push('spatial: '+m);},vec=v=>Array.isArray(v)&&v.length===3&&v.every(Number.isFinite),positive=x=>Number.isFinite(x)&&x>0;
 ok(p.profile?.rasterizer!=='skia','requires Chromium software WebGL');ok(p.spatial?.version===undefined||p.spatial.version==='precision-1','unknown spatial version');ok(!!p.spatial&&Array.isArray(p.spatial.nodes)&&p.spatial.nodes.length>0,'nodes required');if(errors.length)return errors;
 if(p.spatial.clock_origin!==undefined)ok(Number.isFinite(p.spatial.clock_origin)&&p.spatial.clock_origin>=0&&Number.isFinite(p.spatial.clock_duration)&&p.spatial.clock_duration>=p.spatial.clock_origin+p.output.total_frames/30,'invalid source clock');
 if(p.spatial.nodes.some(n=>!n||typeof n!=='object'))return ['spatial: invalid node object'];
 const ids=new Set(p.spatial.nodes.map(n=>n.id));ok(ids.size===p.spatial.nodes.length,'duplicate node id');ok(p.spatial.nodes.length<=2500,'node budget exceeded');
 for(const n of p.spatial.nodes){ok(typeof n.id==='string'&&/^[a-zA-Z0-9-]+$/.test(n.id),'safe node id required');ok(!n.parent||ids.has(n.parent)&&n.parent!==n.id,'unknown/self parent');for(const k of ['position','rotation','scale'])ok(n[k]===undefined||vec(n[k]),'invalid '+k);let seen=new Set([n.id]),cur=n;while(cur?.parent&&ids.has(cur.parent)){if(seen.has(cur.parent)){ok(false,'cyclic parent');break;}seen.add(cur.parent);cur=p.spatial.nodes.find(x=>x.id===cur.parent);}
  const g=n.geometry;if(g){ok(['mesh','box','sphere','cylinder','torus','plane','tube'].includes(g.type),'unknown geometry');if(g.type==='mesh'){ok(Array.isArray(g.vertices)&&g.vertices.length>=9&&g.vertices.length%3===0&&g.vertices.every(Number.isFinite),'invalid mesh');if(g.indices)ok(Array.isArray(g.indices)&&g.indices.length%3===0&&g.indices.every(i=>Number.isInteger(i)&&i>=0&&i<g.vertices.length/3),'invalid indices');}if(['sphere','cylinder','torus','tube'].includes(g.type))ok(positive(g.radius),'positive radius required');if(['box','plane'].includes(g.type))ok(Array.isArray(g.size)&&g.size.length===(g.type==='box'?3:2)&&g.size.every(positive),'invalid size');if(g.type==='tube')ok(Array.isArray(g.points)&&g.points.length>=2&&g.points.every(vec),'invalid tube points');}
  if(n.motion){ok(['wheel','repeat','oscillate'].includes(n.motion.kind),'unknown motion');ok(n.motion.axis===undefined||['x','y','z'].includes(n.motion.axis),'invalid motion axis');if(n.motion.kind==='wheel')ok(positive(n.motion.radius),'invalid wheel radius');if(n.motion.kind==='repeat')ok(Number.isFinite(n.motion.min)&&Number.isFinite(n.motion.max)&&n.motion.max>n.motion.min,'invalid repeat interval');if(n.motion.kind==='oscillate')ok(Number.isFinite(n.motion.amplitude)&&positive(n.motion.frequency),'invalid oscillation');}
  let last=-1;for(const k of n.keyframes||[]){ok(Number.isFinite(k.at)&&k.at>=0&&k.at>last&&k.at<=(p.spatial.clock_duration??p.output.total_frames/30),'node keyframe time');last=k.at;for(const v of ['position','rotation','scale'])ok(k[v]===undefined||vec(k[v]),'node keyframe vector');}
 }
 for(const s of p.scenes){const c=s.spatial;ok(!!c?.camera,'camera required');if(!c?.camera)continue;let last=-1;for(const k of [{at:0,...c.camera},...(c.camera.keyframes||[])]){ok(vec(k.position)&&vec(k.target),'camera vectors required');ok(k.at>=last&&Number.isFinite(k.at)&&k.at<=(s.end-s.start)/30,'camera time range');last=k.at;ok(k.fov===undefined||k.fov>5&&k.fov<140,'camera fov');if(vec(k.position)&&vec(k.target))ok(k.position.some((v,i)=>Math.abs(v-k.target[i])>.001),'zero camera direction');}for(const k of ['speed','acceleration','offset'])ok(c.travel?.[k]===undefined||Number.isFinite(c.travel[k]),'invalid travel');}
 for(const s of p.scenes){const c=s.spatial;if(!c)continue;if(c.plates!==undefined&&!Array.isArray(c.plates)){ok(false,'plates array required');continue;}for(const l of c.plates||[]){const a=p.assets?.find(a=>a.asset_id===l?.asset_id);ok(a?.kind==='raster','plate asset missing');const rect=r=>Array.isArray(r)&&r.length===4&&r.every(Number.isFinite)&&r[2]>0&&r[3]>0;ok(rect(l.rect),'plate rectangle');if(l.source_rect){ok(rect(l.source_rect),'source rectangle');if(a&&rect(l.source_rect))ok(l.source_rect[0]>=0&&l.source_rect[1]>=0&&l.source_rect[0]+l.source_rect[2]<=a.width&&l.source_rect[1]+l.source_rect[3]<=a.height,'source crop outside asset');}if(l.ground_anchors){ok(Array.isArray(l.ground_anchors)&&l.ground_anchors.length===2&&l.ground_anchors.every(x=>vec(x.world)&&Math.abs(x.world[1])<.0001&&Array.isArray(x.source)&&x.source.length===2&&x.source.every(Number.isFinite)),'two ground anchors required');if(l.ground_anchors.length===2)ok(Math.hypot(...l.ground_anchors[0].source.map((v,i)=>v-l.ground_anchors[1].source[i]))>.01,'degenerate ground anchors');}if(l.source_clip)ok(Array.isArray(l.source_clip)&&l.source_clip.length>=3&&l.source_clip.every(v=>Array.isArray(v)&&v.length===2&&v.every(Number.isFinite)),'invalid source clip');if(l.wheels)ok(Array.isArray(l.wheels)&&l.wheels.every(rect),'invalid wheel ellipse');let last=-1;for(const k of l.keyframes||[]){ok(k.at>last&&k.at>=0&&k.at<=(s.end-s.start)/30,'plate keyframe time');last=k.at;ok(k.rect===undefined||rect(k.rect),'plate keyframe rectangle');} }
 }
 for(const s of p.scenes){for(const l of s.spatial?.plates||[]){
  ok(l.wheel_shutter===undefined||Number.isFinite(l.wheel_shutter)&&l.wheel_shutter>=0&&l.wheel_shutter<=1,'wheel shutter range');
  ok(l.opacity===undefined||Number.isFinite(l.opacity)&&l.opacity>=0&&l.opacity<=1,'plate opacity');
  if(l.mirrors!==undefined){ok(Array.isArray(l.mirrors)&&l.mirrors.length<=3,'mirror array/budget');for(const m of l.mirrors){ok(m&&Array.isArray(m.polygon)&&m.polygon.length>=3&&m.polygon.every(v=>Array.isArray(v)&&v.length===2&&v.every(Number.isFinite)),'mirror polygon');ok(vec(m.camera?.position)&&vec(m.camera?.target),'mirror camera');if(vec(m.camera?.position)&&vec(m.camera?.target))ok(m.camera.position.some((v,i)=>Math.abs(v-m.camera.target[i])>.001),'zero mirror direction');ok(m.camera?.fov===undefined||Number.isFinite(m.camera.fov)&&m.camera.fov>5&&m.camera.fov<140,'mirror fov');}}
 }}
 return errors;
}
