import fs from 'node:fs';
import path from 'node:path';
import {serial,write,run,tool,hash} from './io.mjs';
import {assetPath,fileHash} from './media.mjs';
import {checkStructure} from './music-structure.mjs';

export async function createStructureReview(p,m,out,{audio,analysis}={}){
 const result=checkStructure(p,m);if(!result.ok)throw Error(result.errors.join('; '));
 if(fs.existsSync(out))throw Error('Preserve prior structure review');
 if(!audio||!fs.existsSync(audio))throw Error('Selected-interval PCM required');
 const asset=p.assets.find(a=>a.asset_id===m.identity.asset_id),source=assetPath(p,asset);
 if(await fileHash(source)!==m.identity.sha256)throw Error('Original music source hash mismatch');
 fs.mkdirSync(out,{recursive:true});const verified=path.join(out,'music.wav');
 await run(tool('ffmpeg'),['-nostdin','-v','error','-i',source,'-ss',String(m.identity.source_in),'-t',String(m.identity.duration*m.identity.speed),'-vn','-ac','1','-ar','22050','-c:a','pcm_s16le',verified]);
 if(hash(fs.readFileSync(audio))!==hash(fs.readFileSync(verified)))throw Error('Audition WAV does not match the registered selected source interval');
 write(path.join(out,'index.html'),`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>음악 묶음 교정</title><style>body{background:#101517;color:#edf0e8;font:17px system-ui;max-width:1050px;margin:auto;padding:24px}button,input,select,textarea{font:inherit;background:#253035;color:inherit;border:1px solid #63716a;padding:9px;margin:4px;max-width:100%;box-sizing:border-box}button{cursor:pointer}textarea{width:100%;height:360px}audio{width:100%}label{display:inline-block}#status{color:#c7ef7b}li{margin:12px 0}h1{font-size:30px}</style><h1>음악을 먼저 듣고, 묶음을 교정합니다</h1><p>자동 후보는 반복 가능성을 뜻합니다. 첫 박·악기·후렴을 확정하지 않습니다. 이 음원은 선택 구간의 원음 모노 분석본이며, 본편의 볼륨 편집과 구분합니다.</p><audio id="player" controls src="music.wav"></audio><p id="clock"></p><label>원본 시작(초)<input id="from" type="number" step="0.001"></label><label>원본 끝(초)<input id="to" type="number" step="0.001"></label><button id="loop">구절 반복</button><button id="stop">반복 해제</button><button id="add">현재 위치에 경계 추가</button><p>경계는 원본 음원 초 단위입니다. JSON에서 경계를 이동·삭제하고 groups의 start/end를 연결해 묶음을 분할·병합할 수 있습니다. 실제로 들어본 구간에만 listening-corrected를 사용하세요.</p><details><summary>구간별 반복·시작 위치 후보</summary><div id="candidates"></div></details><textarea id="editor" spellcheck="false" aria-label="음악 구조 JSON"></textarea><label><input id="heard" type="checkbox">현재 표시한 경계와 묶음을 실제로 들으며 검토했습니다</label><input id="note" placeholder="검토 구간과 판단 근거" aria-label="청취 근거"><button id="save">교정 JSON 저장</button><p id="status"></p><script>
let m=${serial(m)},analysis=${serial(analysis||{})};const el=id=>document.getElementById(id),player=el('player'),offset=m.identity.source_in;let repeat=false;
el('editor').value=JSON.stringify(m,null,2);el('from').value=offset;el('to').value=Math.min(offset+15,offset+m.identity.duration*m.identity.speed);
el('loop').onclick=()=>{const a=Number(el('from').value),b=Number(el('to').value);if(!(a>=offset&&b>a&&b<=offset+player.duration)){el('status').textContent='원본 범위 안의 시작·끝을 지정하세요';return;}repeat=true;player.currentTime=a-offset;player.play();};el('stop').onclick=()=>repeat=false;
player.ontimeupdate=()=>{el('clock').textContent='원본 '+(offset+player.currentTime).toFixed(3)+'초';if(repeat&&offset+player.currentTime>=Number(el('to').value))player.currentTime=Number(el('from').value)-offset;};
el('add').onclick=()=>{try{m=JSON.parse(el('editor').value);let id='boundary-'+Date.now();m.boundaries.push({id,source_seconds:Number((offset+player.currentTime).toFixed(6)),method:'authored',evidence:'교정 근거를 입력하세요'});m.boundaries.sort((a,b)=>a.source_seconds-b.source_seconds);m.review={status:'pending',note:''};el('heard').checked=false;el('editor').value=JSON.stringify(m,null,2);}catch(e){el('status').textContent=e.message;}};
for(const w of analysis.windows||[]){const box=document.createElement('section'),title=document.createElement('h3');title.textContent='원본 '+w.source_start.toFixed(1)+'–'+w.source_end.toFixed(1)+'초';box.append(title);for(const c of w.recurrence_candidates||[]){const row=document.createElement('p');row.textContent='반복 후보 '+c.period_seconds.toFixed(3)+'초 / 유사도 '+c.similarity+' ';for(const a of c.phase_candidates){const b=document.createElement('button');b.textContent=a.source_seconds.toFixed(3)+'초부터 듣기';b.onclick=()=>{el('from').value=a.source_seconds;el('to').value=Math.min(offset+player.duration,a.source_seconds+c.period_seconds*2);el('loop').click();};row.append(b);}box.append(row);}el('candidates').append(box);}
el('save').onclick=async()=>{try{m=JSON.parse(el('editor').value);const note=el('note').value.trim();if(el('heard').checked&&!note)throw Error('청취 근거를 입력하세요');m.review={status:el('heard').checked?'reviewed':'pending',note};if(el('heard').checked){const text=JSON.stringify({identity:m.identity,boundaries:m.boundaries,groups:m.groups,sections:m.sections});m.review.structure_digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(x=>x.toString(16).padStart(2,'0')).join('');}const url=URL.createObjectURL(new Blob([JSON.stringify(m,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='musical-structure.corrected.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);el('status').textContent='저장했습니다. 적용 시 원음·시간·경계 검사를 다시 수행합니다.';}catch(e){el('status').textContent=e.message;}};
</script></html>`);
 return {page:path.join(out,'index.html'),listening:'pending',structural:result};
}
