import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {read,write,ROOT,hash} from '../lib/io.mjs';import {validate,approvalHash} from '../lib/contract.mjs';import {plan} from '../lib/plan.mjs';
import {browser,pageFor} from '../lib/browser.mjs';import {html} from '../lib/scene.mjs';
const out=path.resolve(process.argv[2]||'direction-test-results'),examples=fs.existsSync(path.join(ROOT,'examples-public'))?'examples-public':'examples',rows=[];
const flight=read(path.join(ROOT,examples,'object-flight.project.json')),water=read(path.join(ROOT,examples,'object-water.project.json'));
async function test(name,fn){try{await fn();rows.push({name,ok:true});console.log('PASS '+name);}catch(e){rows.push({name,ok:false,error:e.message});console.log('FAIL '+name+': '+e.message);}}
await test('both topics have authored object plans',()=>{for(const p of [flight,water])assert.equal(validate(p).ok,true,JSON.stringify(validate(p).errors));});
await test('missing plan fails the strict contract',()=>{const p=structuredClone(flight);delete p.scenes[0].visual_plan;assert.equal(validate(p).ok,false);});
await test('legacy examples are explicitly marked incomplete',()=>{const p=structuredClone(flight);delete p.scenes[0].visual_plan;delete p.direction_contract;const v=validate(p);assert.equal(v.ok,true);assert.ok(v.warnings.length);});
await test('phantom and duplicate object bindings fail',()=>{const p=structuredClone(flight);p.scenes[0].visual_plan.objects[0].bindings=['does-not-exist'];assert.equal(validate(p).ok,false);const q=structuredClone(flight);q.scenes[0].composition.layers[1].id=q.scenes[0].composition.layers[0].id;assert.equal(validate(q).ok,false);});
await test('calling a caption an aircraft does not satisfy drawing requirement',()=>{const p=structuredClone(flight);p.scenes[0].visual_plan.objects.find(o=>o.id==='plane').bindings=['copy-2'];assert.equal(validate(p).ok,false);});
await test('unmapped content and invalid beat windows fail',()=>{const p=structuredClone(flight);p.scenes[0].visual_plan.content_links.pop();assert.equal(validate(p).ok,false);const q=structuredClone(flight);q.scenes[0].visual_plan.beats[0].window=[14,16];assert.equal(validate(q).ok,false);});
await test('malformed plan returns validation error',()=>{for(const field of ['objects','beats','continuity','content_links']){const p=structuredClone(flight);p.scenes[0].visual_plan[field]='invalid';assert.equal(validate(p).ok,false);}});
await test('data field must bind to its own object',()=>{const p=structuredClone(flight);p.scenes[0].visual_plan.objects[0].information[0].layer_id='aircraft';assert.equal(validate(p).ok,false);});
await test('changing visual intent invalidates prior approval',()=>{const p=structuredClone(flight);p.approval={hash:approvalHash(p)};p.scenes[0].visual_plan.objects[0].features.push('new feature');assert.equal(validate(p).ok,false);});
await test('reviewable plan contains subjects, values, actions and continuity',()=>{const f=path.join(out,'plan.html');plan(flight,f);const h=fs.readFileSync(f,'utf8');for(const s of ['공항 출발 안내표','YE101','08:40','빈 표시 셀','같은 SVG 객체'])assert.ok(h.includes(s),s);assert.ok(!h.includes('중심 대상의 위치와 빛 연결'));});
await test('real bound layers appear at required beats and preserve data',async()=>{const b=await browser();try{for(const [name,p,samples]of [['flight',flight,[[2.5,['departure-board','flight-row-0']],[7.5,['globe','route-tokyo','aircraft']],[12.5,['aircraft']]]],['water',water,[[2.5,['pipes','inlet-water']],[6,['sieve','incoming-particle-0']],[10.5,['outlet-water','collected-water']]]]]){const f=path.join(out,name+'.html');write(f,html(p,{controls:false}));const {page,context}=await pageFor(b,f,960,540);try{for(const [t,ids]of samples){await page.evaluate(t=>__seek(t),t);for(const id of ids){const o=await page.locator('[data-layer-id="'+id+'"]').evaluate(n=>{const r=n.getBoundingClientRect();return {opacity:Number(n.getAttribute('opacity')),area:r.width*r.height};});assert.ok(o.opacity>.1&&o.area>10,name+' '+id+' '+t);}}
if(name==='flight'){await page.evaluate(()=>__seek(2.5));const row=await page.locator('[data-layer-id="flight-row-0"]').textContent();for(const s of ['08:40','YE101','TOKYO NRT','07','BOARDING'])assert.ok(row.includes(s));await page.evaluate(()=>__seek(7.5));assert.equal(await page.locator('[data-layer-id="route-number"]').textContent(),'YE101   /   08:40   /   GATE 07');}
const hashes=[];for(const t of [2.5,8.2,2.5]){await page.evaluate(t=>__seek(t),t);hashes.push(hash(await page.locator('#stage').screenshot()));}assert.equal(hashes[0],hashes[2]);assert.notEqual(hashes[0],hashes[1]);}finally{await context.close();}}}finally{await b.close();}});
const report={ok:rows.every(r=>r.ok),rows,scope:'Structural, visible geometry and data consistency. Not artistic approval or semantic recognition.'};write(path.join(out,'direction-tests.json'),report);if(!report.ok)process.exitCode=1;
