import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';
import {ROOT,read,readProject,write,hash,mkdir,settings,run} from '../lib/io.mjs';
import {validate,approvalHash,revise,requireValid} from '../lib/contract.mjs';
import {sceneKey,html} from '../lib/scene.mjs';import {render,snapshot,probe} from '../lib/render.mjs';
import {browser,pageFor,serve} from '../lib/browser.mjs';import {catalog} from '../lib/catalog.mjs';import {audio} from '../lib/audio.mjs';import {imageAssets} from '../lib/assets.mjs';
const out=path.resolve(process.argv[2]||fs.mkdtempSync(path.join(os.tmpdir(),'motion-test-')));mkdir(out);const rows=[];
async function test(name,fn){if(process.env.MOTION_TEST&&!name.includes(process.env.MOTION_TEST))return;try{await fn();rows.push({name,ok:true});console.log('PASS '+name);}catch(e){rows.push({name,ok:false,error:e.message});console.log('FAIL '+name+': '+e.message);}}
const exampleDir=fs.existsSync(path.join(ROOT,'examples-public'))?'examples-public':'examples';
const example=name=>readProject(path.join(ROOT,exampleDir,name+'.project.json'));
const base=example('journey');
function tiny(){const p=structuredClone(base);p.project_id='release-probe';p.routes=['video-editing'];p.output.total_frames=180;p.assets=[];p.content_units=p.content_units.slice(0,2).map((c,i)=>({...c,display_text:['길을 잇다','함께 가다'][i],source_text:['길을 잇다','함께 가다'][i],copy_lock:false}));p.required_content_ids=p.content_units.map(c=>c.content_id);p.scenes=p.content_units.map((c,i)=>({id:'cut-'+i,start:i*90,end:(i+1)*90,mode:'composite',content_ids:[c.content_id],composition:{width:1920,height:1080,background:i?'#e7e2d4':'#12352c',layers:[{kind:'svg',svg:'<path d="M120 540H1800" fill="none" stroke="#c0aa76" stroke-width="6" pathLength="1"/>',draw:0,keyframes:[{at:1,draw:1}]},{kind:'text',content_id:c.content_id,position:[960,500],size:100,color:i?'#12352c':'#e7e2d4',opacity:0,keyframes:[{at:.5,opacity:1}]}]}}));p.audio={bpm:84,motif:[62,65,69],sections:[{start:0,end:6,energy:.3,chord:[50,57,62]}],cues:[{time:3,kind:'chime'}],silence:[]};delete p.approval;delete p.status;return p;}
function authorize(p){delete p.approval;p.approval={hash:approvalHash(p),by:'automated-test',note:'Synthetic test only; no user/artistic approval',at:new Date().toISOString()};return p;}
await test('upstream inventory preserved',()=>{const c=catalog();assert.equal(c.effects.length,637);assert.equal(c.effects.filter(e=>e.render==='done').length,128);assert.equal(c.recipes.length,11);assert.equal(c.routes.length,7);assert.equal(hash(fs.readFileSync(path.join(ROOT,'vendor/awesome-ai-motion/index.json'))),'86129d75e19c7953e88689f9f0ffc1f52409a4dba3a50736cbe8096d2faf88cd');});
await test('all public examples valid and unapproved',()=>{for(const name of ['journey','editorial','material','image-flow','flow-transfer','water','object-flight','object-water']){const p=example(name),v=validate(p);assert.equal(v.ok,true,name+JSON.stringify(v.errors));assert.equal(p.approval,undefined);}});
await test('approval, source locks and unsafe SVG enforced',()=>{const p=tiny();assert.throws(()=>requireValid(p,true));authorize(p);p.title+=' changed';assert.equal(validate(p).ok,false);delete p.approval;p.content_units[0].copy_lock=true;p.content_units[0].display_text='변경';assert.equal(validate(p).ok,false);const q=tiny();q.scenes[0].composition.layers[0].svg='<image href="https://example.invalid/x.png"/>';assert.equal(validate(q).ok,false);});
await test('only changed cut invalidates; visual settings invalidate',()=>{const p=tiny(),q=structuredClone(p),profile={width:1280,height:720};q.content_units[0].display_text='길을 따라';assert.notEqual(sceneKey(p,p.scenes[0],profile,false),sceneKey(q,q.scenes[0],profile,false));assert.equal(sceneKey(p,p.scenes[1],profile,false),sceneKey(q,q.scenes[1],profile,false));q.seed++;assert.notEqual(sceneKey(p,p.scenes[1],profile,false),sceneKey(q,q.scenes[1],profile,false));q.profile.rasterizer='skia';assert.notEqual(sceneKey(p,p.scenes[1],profile,false),sceneKey(q,q.scenes[1],profile,false));});
await test('revision preserves input and relocates project assets',()=>{const p=example('flow-transfer'),a=p.assets[0],original=path.join(out,'asset-project/source.json'),changed=path.join(out,'other/revised.json');mkdir(path.dirname(original));const source=path.join(ROOT,a.path.slice(6));fs.copyFileSync(source,path.join(path.dirname(original),'art.png'));a.path='art.png';write(original,p);const before=hash(fs.readFileSync(original));revise(original,p.content_units[0].content_id,'연기의 새로운 흐름',changed);assert.equal(hash(fs.readFileSync(original)),before);assert.ok(Object.keys(imageAssets(readProject(changed))).length);assert.equal(read(changed).approval,undefined);});
await test('HTTP seeking range, HEAD, invalid ranges and traversal',async()=>{write(path.join(out,'range.bin'),Buffer.from('0123456789'));const s=await serve(out);try{const response=await fetch(s.url+'/range.bin',{headers:{Range:'bytes=2-5'}});assert.equal(response.status,206);assert.equal(await response.text(),'2345');assert.equal(response.headers.get('content-range'),'bytes 2-5/10');assert.equal((await fetch(s.url+'/range.bin',{headers:{Range:'bytes=20-30'}})).status,416);assert.equal((await fetch(s.url+'/range.bin',{method:'HEAD'})).headers.get('content-length'),'10');assert.equal((await fetch(s.url+'/%2e%2e%2foutside')).status,404);}finally{await new Promise(resolve=>s.server.close(resolve));}});
await test('absolute-time SVG seek and web controls',async()=>{const p=tiny(),f=path.join(out,'time.html');write(f,html(p));const b=await browser();try{const {page,context}=await pageFor(b,f,960,540);let first=null;for(const t of [1.3,4.2,.1,1.3]){await page.evaluate(t=>window.__seek(t),t);const h=hash(await page.locator('#stage').screenshot());if(first===null)first=h;else if(t===1.3)assert.equal(h,first);}assert.equal(await page.locator('#music').evaluate(a=>a.paused),true);await page.evaluate(()=>window.__progress(.75));assert.equal(await page.evaluate(()=>window.__state.frame),135);await context.close();}finally{await b.close();}});
await test('general image flow uses arbitrary asset ID and zero intensity',async()=>{const p=example('flow-transfer'),f=path.join(out,'flow.html');write(f,html(p,{controls:false}));const b=await browser();try{const {page,context}=await pageFor(b,f,960,540);const values=await page.evaluate(()=>{const id=PROJECT.assets[0].asset_id,m={preset:'smoke',intensity:.8,speed:.7};const a=__flowImage(id,1.2,m);__flowImage(id,4,m);const z=__flowImage(id,1.2,m),next=__flowImage(id,2.8,m),off1=__flowImage(id,0,{...m,intensity:0}),off2=__flowImage(id,2,{...m,intensity:0});return {same:a===z,moving:a!==next,off:off1===off2,stats:__flowStats,id};});assert.equal(values.same,true);assert.equal(values.moving,true);assert.equal(values.off,true);assert.equal(values.stats.foldover,false);assert.equal(values.id,'new-flow-art');await context.close();}finally{await b.close();}});
await test('audio repeatability and bounded samples',async()=>{const p=tiny();p.audio.silence=[{start:1,end:1.2}];p.audio.cues=[{time:.9,kind:'impact',duration:.7}];const a=await audio(p,path.join(out,'audio-a')),b=await audio(p,path.join(out,'audio-b'));assert.deepEqual(a.sha256,b.sha256);assert.ok(a.peak_dbfs<0);assert.equal(fs.readFileSync(a.files[2]).readInt16LE(44+Math.round(1.1*48000)*4),0);assert.equal(fs.readFileSync(a.files[1]).readInt16LE(44+Math.round(1.1*48000)*4),0);assert.equal(fs.statSync(a.files[2]).size,44+6*48000*4);});
await test('interrupted render resumes completed cut; changed cut rerenders',async()=>{const p=authorize(tiny()),dir=path.join(out,'render');await assert.rejects(render(p,dir,{draft:true,stopAfterFrames:95}),/interruption/);const done=await render(p,dir,{draft:true});assert.equal(done.log.clips[0].reused,true);assert.equal(done.log.clips[1].reused,false);const previous=hash(fs.readFileSync(done.final));p.content_units[0].display_text='길을 따라';authorize(p);const changed=await render(p,dir,{draft:true});assert.equal(changed.log.clips[0].reused,false);assert.equal(changed.log.clips[1].reused,true);assert.equal(hash(fs.readFileSync(done.final)),previous);const info=await probe(changed.final);assert.equal(info.streams.find(s=>s.codec_type==='video').nb_frames,'180');});
await test('optional Skia actual frames and MP4',async()=>{const cfg=settings();if(!cfg.skiaPath&&!cfg.python){rows.push({name:'Skia environment',skipped:true,reason:'Optional Python not configured'});return;}const p=tiny();p.profile.rasterizer='skia';authorize(p);let first;for(const [i,t]of [1.3,4.2,1.3].entries()){const f=path.join(out,'native-'+i+'.png');await snapshot(p,f,{time:t,width:960,height:540});const h=hash(fs.readFileSync(f));if(i===0)first=h;if(i===2)assert.equal(h,first);}const r=await render(p,path.join(out,'skia-render'),{draft:true});assert.equal(r.log.profile.rasterizer,'skia');assert.equal(r.log.totalFrames,180);});
const report={at:new Date().toISOString(),rows,ok:rows.every(r=>r.ok||r.skipped),scope:'Automated implementation checks; aesthetic and human listening review separate'};write(path.join(out,'release-tests.json'),report);console.log(JSON.stringify({ok:report.ok,out}));if(!report.ok)process.exitCode=1;



