import assert from 'node:assert/strict';
import {compileRhythm,rhythmCheck,rhythmReviewFrames} from '../lib/rhythm-score.mjs';
const sha='a'.repeat(64),vsha='b'.repeat(64),clone=structuredClone;
function fixture(){return {schema_version:'3.1.0',output:{fps:30,total_frames:5400},assets:[{asset_id:'song',kind:'audio',sha256:sha},{asset_id:'film',kind:'video',sha256:vsha,duration:240}],audio:{clips:[{asset_id:'song',bus:'music',start:0,source_in:100,duration:180}]},scenes:[{id:'a',start:0,end:900,composition:{layers:[{id:'word',kind:'text'},{id:'v',kind:'video',asset_id:'film',source_in:0}]}},{id:'b',start:900,end:5400,composition:{layers:[{id:'mark',kind:'svg'}]}}],rhythm_score:{version:'music-impact-v1',music:{asset_id:'song',clip_index:0,sha256:sha},tolerance_frames:0,events:[{id:'hit',source_seconds:100+60/133*8,role:'accent',method:'estimated-grid',confidence:.6,evidence:'Explicit test clock'}],bindings:[{id:'reveal',event_id:'hit',scene_id:'a',target:{kind:'layer',layer_id:'word'},prepare_frames:3,hold_frames:15,before:{opacity:0,scale:.9},after:{opacity:1,scale:1},reason:'Meaningful graphic arrives on selected accent'}],holds:[{scene_id:'b',start_frame:1000,end_frame:1300,reason:'Sustained story image across many music pulses'}]}};}
let count=0;function test(name,fn){fn();count++;console.log('PASS rhythm '+name);}
test('legacy and malformed safe',()=>{assert.equal(rhythmCheck({}).ok,true);assert.equal(rhythmCheck({rhythm_score:null}).ok,false);});
test('compile pure, independent of playback history',()=>{const p=fixture(),saved=JSON.stringify(p),a=compileRhythm(p),b=compileRhythm(p);assert.equal(JSON.stringify(p),saved);assert.deepEqual(a,b);assert.equal(rhythmCheck(a).ok,true);assert.equal(a.approval,undefined);});
test('absolute beat clock no cumulative rounding drift',()=>{const p=fixture();p.rhythm_score.events[0].source_seconds=100+380*60/133;p.rhythm_score.bindings[0].scene_id='b';p.rhythm_score.bindings[0].target.layer_id='mark';const q=compileRhythm(p),r=rhythmCheck(q);assert.equal(r.bindings[0].impact_frame,Math.round(380*60/133*30));assert(Math.abs(r.bindings[0].quantization_ms)<=1000/60);});
test('six visual drift mutants rejected',()=>{for(const offset of [-4,-2,-1,1,2,4]){const p=compileRhythm(fixture());p.scenes[0].composition.layers[0].keyframes[1].at+=offset/30;assert.equal(rhythmCheck(p).ok,false);}});
test('music source change, trim and speed invalidate',()=>{for(const mutate of [p=>p.assets[0].sha256='c'.repeat(64),p=>p.audio.clips[0].source_in+=1,p=>p.audio.clips[0].speed=.8]){const p=compileRhythm(fixture());mutate(p);assert.equal(rhythmCheck(p).ok,false);}});
test('gain change preserves picture mapping',()=>{const p=compileRhythm(fixture());p.audio.clips[0].gain_db=-10;assert.equal(rhythmCheck(p).ok,true);});
test('out of range, duplicate ownership, clipped holds',()=>{for(const mutate of [p=>p.rhythm_score.events[0].source_seconds=99,p=>p.rhythm_score.bindings.push(clone(p.rhythm_score.bindings[0])),p=>p.rhythm_score.bindings[0].hold_frames=900]){const p=fixture();mutate(p);assert.throws(()=>compileRhythm(p));}});
test('authored animation never silently overwritten',()=>{const p=fixture();p.scenes[0].composition.layers[0].keyframes=[{at:1,opacity:.5}];assert.throws(()=>compileRhythm(p),/overwrite/);});
test('cut changes both adjacent boundaries, preserves hold intent',()=>{const p=fixture();p.rhythm_score.events[0].source_seconds=130;p.rhythm_score.bindings=[{id:'cut',event_id:'hit',scene_id:'b',target:{kind:'cut'},reason:'New story phase arrives on accent'}];assert.equal(rhythmCheck(compileRhythm(p)).ok,true);p.rhythm_score.events[0].source_seconds=145;assert.throws(()=>compileRhythm(p),/sustained/);});
test('video contact source map and tamper',()=>{const p=fixture();p.rhythm_score.bindings=[{id:'contact',event_id:'hit',scene_id:'a',target:{kind:'video',layer_id:'v'},source_sha256:vsha,source_event_seconds:12,reason:'Foot contacts crank on selected musical event'}];const q=compileRhythm(p);assert.equal(rhythmCheck(q).ok,true);q.scenes[0].composition.layers[1].source_in+=.2;assert.equal(rhythmCheck(q).ok,false);});
test('camera arrival and deterministic review frame indexes',()=>{const p=fixture();p.rhythm_score.bindings=[{id:'cam',event_id:'hit',scene_id:'a',target:{kind:'camera'},prepare_frames:30,hold_frames:10,before:{zoom:1,focus:[.5,.5]},after:{zoom:1.4,focus:[.6,.5]},reason:'Arrive at wheel hub, maintain stable composition'}];const q=compileRhythm(p);assert.equal(rhythmCheck(q).ok,true);assert.equal(rhythmReviewFrames(q).length,3);});
test('malformed holds and word/rhythm collision rejected',()=>{const p=fixture();p.rhythm_score.holds={};assert.equal(rhythmCheck(p).ok,false);const q=fixture();q.sync_score={cues:[{scene_id:'a',layer_id:'word'}]};assert.throws(()=>compileRhythm(q),/ownership/);});
test('video action cannot select negative source handles',()=>{const p=fixture();p.rhythm_score.bindings=[{id:'clip',event_id:'hit',scene_id:'a',target:{kind:'video',layer_id:'v'},source_sha256:vsha,source_event_seconds:0,reason:'Source action starts too early for selected shot'}];assert.throws(()=>compileRhythm(p),/handles/);});
console.log('rhythm-score: '+count+' tests passed');
