import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {spatialErrors} from '../lib/spatial.mjs';import {editErrors} from '../lib/audio-edit.mjs';import {ROOT,write} from '../lib/io.mjs';
const p={renderer:'spatial-three',profile:{gpu:false,jobs:1},output:{total_frames:120},spatial:{nodes:[{id:'ground',geometry:{type:'plane',size:[8,30]}}]},scenes:[{start:0,end:120,spatial:{camera:{position:[0,2,5],target:[0,0,0]},plates:[{asset_id:'plate',rect:[0,0,1920,1080],source_rect:[0,0,100,100],ground_anchors:[{source:[10,90],world:[0,0,-1]},{source:[90,90],world:[0,0,1]}]}]}}],assets:[{asset_id:'plate',kind:'raster',width:100,height:100}],audio:{}};
const rows=[],test=(name,fn)=>{fn();rows.push({name,ok:true});console.log('PASS '+name);};test('minimal spatial data',()=>assert.deepEqual(spatialErrors(p),[]));
for(const [name,mut]of [
 ['null node',q=>q.spatial.nodes=[null]],['node keyframes scalar',q=>q.spatial.nodes[0].keyframes=7],['mesh without vertices',q=>q.spatial.nodes[0].geometry={type:'mesh',indices:[0,1,2]}],['null plate',q=>q.scenes[0].spatial.plates=[null]],['null ground anchor',q=>q.scenes[0].spatial.plates[0].ground_anchors=[null,null]],['zero camera direction',q=>q.scenes[0].spatial.camera.target=[0,2,5]],['negative shutter',q=>q.scenes[0].spatial.plates[0].wheel_shutter=-1],['mirror without camera',q=>q.scenes[0].spatial.plates[0].mirrors=[{polygon:[[0,0],[10,0],[10,10]]}]],['zero mirror direction',q=>q.scenes[0].spatial.plates[0].mirrors=[{polygon:[[0,0],[10,0],[10,10]],camera:{position:[0,1,0],target:[0,1,0]}}]]
])test('reject '+name,()=>{const q=structuredClone(p);mut(q);assert(spatialErrors(q).length,name);});
test('audio editing is optional',()=>assert.deepEqual(editErrors(p),[]));
test('audio edit refuses absent rights',()=>{const q=structuredClone(p);q.assets.push({asset_id:'sound',kind:'audio',path:'sound.wav',sha256:'0'.repeat(64)});q.audio.clips=[{asset_id:'sound',bus:'music',start:0,source_in:0,duration:4}];assert(editErrors(q).some(e=>e.includes('permission')));});
test('schema exposes spatial camera and all supported new cues',()=>{const schema=JSON.parse(fs.readFileSync(path.join(ROOT,'contracts/project.schema.json')));assert(schema.properties.scenes.items.properties.spatial.properties.camera);for(const k of ['drive','wind','passby'])assert(schema.properties.audio.properties.cues.items.properties.kind.enum.includes(k));});
write(path.resolve(process.argv[2]||'spatial-test-results')+'/report.json',{ok:true,checks:rows.length,rows,note:'Data safety only. Runtime rendering, contact appearance and vehicle fidelity require separate evidence.'});
