import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';
import {compileSyncScore,syncScoreCheck,syncReviewFrames} from '../lib/sync-score.mjs';
import {ROOT,read,hash} from '../lib/io.mjs';
const sha='1'.repeat(64);
const cue=(id,scene,layer,at)=>({id,text:id,scene_id:scene,layer_id:layer,clip_index:0,source:{asset_id:'voice',sha256:sha,sample_rate:48000,onset_sample:at*48000,anchor_sample:(at+.01)*48000,release_sample:(at+.3)*48000,method:'isolated-speech',confidence:.6,evidence:'Synthetic unit-test fixture; no human listening'},prepare_frames:3,exit_frames:3,hold_until_frame:50,anticipation:{x:0,y:60,scale:1.2,opacity:0},landing:{x:0,y:0,scale:1,opacity:1}});
function fixture(){return {schema_version:'3.1.0',renderer:'vector-composite',output:{fps:30,total_frames:120},content_units:[],assets:[{asset_id:'voice',kind:'audio',sha256:sha}],audio:{clips:[{asset_id:'voice',bus:'voice',source_in:0,start:0,duration:4}]},scenes:[{id:'a',start:0,end:60,composition:{layers:[{id:'one',kind:'text',text:'one'},{id:'object',kind:'svg',svg:'<circle/>'}]}},{id:'b',start:60,end:120,composition:{layers:[{id:'next-object',kind:'svg',svg:'<circle/>'}]}}],sync_score:{version:'word-impact-v1',tolerance_frames:0,cues:[cue('one','a','one',1)],phrases:[{id:'phrase',cue_ids:['one'],release_frame:50,transition_start_frame:52,arrival_frame:60,next_scene_id:'b',bridge:{out_layer:'object',in_layer:'next-object',relation:'same-object',reason:'Circle maintains identity',out_anchor:[.5,.5],in_anchor:[.5,.5]}}]}};}
const tests=[];
function test(name,fn){fn();tests.push(name);console.log('PASS sync-score '+name);}
test('malformed containers report errors rather than throwing',()=>{for(const change of [p=>delete p.output,p=>delete p.scenes,p=>p.audio.clips=null,p=>p.sync_score.cues=[null],p=>p.sync_score.phrases=[null]]){const p=fixture();change(p);assert.equal(syncScoreCheck(p).ok,false);}});
test('instant word has no duplicate preparation keyframe',()=>{const p=fixture();p.sync_score.cues[0].prepare_frames=0;const q=compileSyncScore(p),k=q.scenes[0].composition.layers[0].keyframes;assert.ok(k.every((v,i)=>i===0||v.at>k[i-1].at));assert.equal(k[0].at,1);assert.equal(k[0].ease,'hold');});
test('sample clock quantizes to nearest frame and retains residual',()=>{const p=compileSyncScore(fixture()),r=syncScoreCheck(p);assert.ok(r.ok,JSON.stringify(r));assert.equal(r.cues[0].impact_frame,30);assert.ok(Math.abs(r.cues[0].quantization_ms+10)<1e-7);assert.ok(r.warnings.some(x=>x.includes('listening')));});
test('compiler preserves input and clears prior approval',()=>{const p=fixture(),before=hash(p);p.approval={hash:'fake'};const q=compileSyncScore(p);assert.equal(q.approval,undefined);delete p.approval;assert.equal(hash(p),before);assert.equal(q.scenes[0].composition.layers[0].keyframes[1].at,1);});
test('source trim and speed use source time not raw song offset',()=>{const p=fixture();Object.assign(p.audio.clips[0],{source_in:.5,start:.2,speed:2,duration:1.5});p.sync_score.phrases=[];const q=compileSyncScore(p);assert.equal(syncScoreCheck(q).cues[0].expected_frame,14);});
test('early/late 1 2 4 frame injection is rejected',()=>{for(const n of [-4,-2,-1,1,2,4]){const p=fixture();p.sync_score.cues[0].impact_offset_frames=n;assert.ok(syncScoreCheck(p,{requireCompiled:false}).errors.some(x=>x.includes('differs from audio')));}});
test('changing materialized keyframes cannot pass by preserving metadata',()=>{const p=compileSyncScore(fixture());p.scenes[0].composition.layers[0].keyframes[1].at+=1/30;assert.ok(syncScoreCheck(p).errors.some(x=>x.includes('rendered keyframes')));});
test('audio retime and hash replacement make materialization stale',()=>{for(const change of [p=>p.audio.clips[0].start+=.02,p=>p.assets[0].sha256='2'.repeat(64)]){const p=compileSyncScore(fixture());change(p);assert.equal(syncScoreCheck(p).ok,false);}});
test('clipped final word and delayed handoff rejected',()=>{const p=fixture();p.sync_score.phrases[0].release_frame=30;assert.equal(syncScoreCheck(p,{requireCompiled:false}).ok,false);p.sync_score.phrases[0].release_frame=50;p.sync_score.phrases[0].arrival_frame=64;assert.equal(syncScoreCheck(p,{requireCompiled:false}).ok,false);});
test('source range, word identity and target bindings validated',()=>{for(const change of [p=>p.sync_score.cues[0].source.release_sample=5*48000,p=>p.sync_score.cues[0].text='mismatch',p=>p.sync_score.cues[0].layer_id='absent',p=>p.sync_score.cues.push(p.sync_score.cues[0])]){const p=fixture();change(p);assert.equal(syncScoreCheck(p,{requireCompiled:false}).ok,false);}});
test('portrait requires same word clock',()=>{const p=fixture();p.scenes[0].portrait_composition=structuredClone(p.scenes[0].composition);const q=compileSyncScore(p);assert.ok(syncScoreCheck(q).ok);q.scenes[0].portrait_composition.layers[0].keyframes[0].at+=.01;assert.equal(syncScoreCheck(q).ok,false);});
test('unrequested old projects remain valid and evidence contains exact boundary frames',()=>{assert.equal(syncScoreCheck({}).ok,true);const frames=syncReviewFrames(compileSyncScore(fixture()));assert.ok([29,30,31,59,60].every(x=>frames.includes(x)));assert.equal(new Set(frames).size,frames.length);});
test('project schema embeds exactly the offline public score schema',()=>{const s=read(path.join(ROOT,'contracts/sync-score.schema.json'));delete s.$id;delete s.$schema;assert.deepEqual(read(path.join(ROOT,'contracts/project-3.1.schema.json')).$defs.sync_score,s);});
console.log(JSON.stringify({ok:true,tests:tests.length,scope:'Structural timing/error injection. No aesthetic or listening claim.'}));
