import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';
import {TECHNIQUES,technique,techniqueCoverage} from '../lib/techniques.mjs';import {search,catalog} from '../lib/catalog.mjs';import {validate} from '../lib/contract.mjs';import {write,hash} from '../lib/io.mjs';import {html} from '../lib/scene.mjs';import {browser,pageFor} from '../lib/browser.mjs';
import {snapshot} from '../lib/render.mjs';
const out=fs.mkdtempSync(path.join(os.tmpdir(),'motion-techniques-')),b=await browser(),rows=[];
const subject={id:'subject',kind:'svg',svg:'<circle cx="900" cy="500" r="140" fill="#a9dfee"/><path d="M700 700H1100" stroke="#ffad64" stroke-width="10"/>'};
try{for(const [id,spec]of Object.entries(TECHNIQUES)){
 const input={id,instance:'test-'+id,inputs:{layers:[subject,{...subject,id:'second',svg:'<rect x="1200" y="300" width="120" height="200" fill="#ffad64"/>'}],text:'서울',content_id:'caption',position:[900,600],size:100,rect:[0,0,1920,1080],values:[4,7,3],basis:'Explicit illustrative values',point:[900,500],center:[900,500],count:8,reason:'Synthetic adapter contract and seek reproducibility test'},parameters:{duration:1,color:'#7ed4fa',amount:120,seed:44}};
 if(id==='crt-scanlines')input.inputs.size=[1920,1080];
 const made=technique(input);assert.deepEqual(technique(input),made,'seeded output must repeat');assert(catalog().effects.some(e=>e.slug===made.receipt.card_id));
 const p={schema_version:'3.1.0',project_id:'technique-test',title:'Adapter test',direction:'Synthetic correctness fixture; not aesthetic acceptance',renderer:'vector-composite',timeline_semantics:'segments-v1',editing_contract:'shot-rhythm-v1',visual_policy:'strict_svg',render_network:'local_only',seed:44,routes:['video-editing'],profile:{jobs:1,gpu:false},output:{width:1920,height:1080,fps:30,total_frames:180},sources:[{source_id:'authored',title:'Test only',retrieval_state:'authored'}],content_units:[],required_content_ids:[],assets:[],events:[],scenes:[{id:'a',start:0,end:90,mode:'composite',content_ids:[],shot_role:'action',composition:{width:1920,height:1080,background:'#07111a',layers:[subject]}},{id:'b',start:90,end:180,mode:'composite',content_ids:[],shot_role:'action',composition:{width:1920,height:1080,background:'#173a48',layers:made.layers.length?made.layers:[subject]}}],audio:{bpm:120,motif:[60],sections:[{start:0,end:6,energy:0}]}};
 if(made.transition){p.renderer='hybrid-composite';p.scenes[1].transition_in=made.transition;}
 if(id==='lower-third-reveal'){p.content_units=[{content_id:'caption',source_ref:'authored',source_text:'도시',display_text:'도시',copy_lock:false}];p.required_content_ids=['caption'];p.scenes[1].content_ids=['caption'];p.scenes[1].shot_role='reading';p.scenes[1].reading_windows=[{content_id:'caption',start:1,end:3}];}
 p.techniques=[{...made.receipt,scene_id:'b'}];assert.deepEqual(techniqueCoverage(p).errors,[]);assert(validate(p).ok,JSON.stringify(validate(p).errors));
 if(made.transition){const hashes=[];for(const [i,time]of [3,3.5,4.1,3.5].entries()){const f=path.join(out,'fade-'+i+'.png');await snapshot(p,f,{time,width:64,height:36});hashes.push(hash(fs.readFileSync(f)));}assert.equal(hashes[1],hashes[3]);assert.equal(new Set(hashes.slice(0,3)).size,3);rows.push({id,family:spec.family,reorderedSnapshot:true,actualHybridTransition:true});console.log('PASS '+id);continue;}
 const f=path.join(out,id+'.html');write(f,html(p,{controls:false}));const {page,context,errors}=await pageFor(b,f,320,180);
 const result=await page.evaluate(()=>{const node=document.querySelector('#stage');window.__seek(4.3);const a=node.innerHTML;window.__seek(3.2);const different=node.innerHTML;window.__static(4.3);const same=a===node.innerHTML;window.__progress(4.3/6);return {same,progress:a===node.innerHTML,changed:a!==different,finite:!node.innerHTML.includes('NaN')};});
 assert(result.same&&result.progress&&result.finite);assert.deepEqual(errors,[]);await page.screenshot({path:path.join(out,id+'.png')});await context.close();rows.push({id,family:spec.family,...result});console.log('PASS '+id);
}
assert.equal(new Set(rows.map(x=>x.family)).size,15);assert.equal(search('',637,{status:'executable',engine:'chromium'}).length,14);assert.equal(search('',637,{status:'executable',engine:'ffmpeg'}).length,1);assert.equal(search('',637,{status:'aesthetic'}).length,0);assert.throws(()=>technique({id:'bar-grow',instance:'bad',inputs:{values:[1]}}));assert.throws(()=>search('',30,{status:'invented'}));write(path.join(out,'adapter-tests.json'),{rows,scope:'contract/DOM execution/time-scroll-still identity; crossfade uses actual hybrid frames; visual aesthetics pending'});console.log(JSON.stringify({passed:rows.length,out}));
}finally{await b.close();}
