/* Non-browser structural and state checks. Visual/interaction tests belong to CUA. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {create,reduce}=require('./assets/state.js');
let checks=0;function ok(value,message){assert.ok(value,message);checks++;}
let s=create([0,3,0,4]);s=reduce(s,{type:'next'});ok(s.current===1&&s.steps[1]===1,'first reveal pre-exposed');s=reduce(s,{type:'next'});ok(s.current===1&&s.steps[1]===2,'advance semantic step');s=reduce(s,{type:'previous'});ok(s.steps[1]===1,'reverse a step');s=reduce(s,{type:'next'});s=reduce(s,{type:'next'});s=reduce(s,{type:'next'});ok(s.current===2,'move only after final reveal');s=reduce(s,{type:'previous'});ok(s.current===1&&s.steps[1]===3,'backward enters complete previous slide');s=reduce(s,{type:'view',view:'keep'});ok(s.views[1]==='keep','click and key share view action');let original=JSON.stringify(s);reduce(s,{type:'reset'});ok(JSON.stringify(s)===original,'pure reducer does not mutate original');ok(JSON.stringify(reduce(s,{type:'goto',index:NaN}))===original,'invalid goto ignored');ok(JSON.stringify(reduce(s,{type:'goto',index:2.5}))===original,'fractional goto ignored');ok(JSON.stringify(reduce(s,{type:'view',view:'injected'}))===original,'unknown view ignored');
const css=fs.readFileSync(path.join(__dirname,'assets/deck.css'),'utf8'),js=fs.readFileSync(path.join(__dirname,'assets/controller.js'),'utf8');
ok(!/localStorage|sessionStorage|indexedDB|fetch\(|XMLHttpRequest|WebSocket/.test(js),'runtime never persists notes or calls network');ok(!/beforeprint|afterprint/.test(js),'print has no state-mutating event path');ok(js.includes("dialogs.some(d=>d.open)"),'modal owns keyboard');ok(js.includes('e.isComposing'),'IME guard');ok(js.includes('input,textarea,select,[contenteditable]')&&js.includes("[' ','enter','tab'].includes(key)"),'form ownership and native activation preserved');ok(css.includes('prefers-reduced-motion:reduce')&&!css.match(/prefers-reduced-motion:reduce[^}]*opacity:1/),'reduced motion does not skip steps');
ok(js.includes("clone.remove")||js.includes("finally{probe.remove();}"),'fit probe is removed');ok(js.includes('readingObserver?.takeRecords()')&&js.includes('generation!==readingGeneration'),'stale reading observations are rejected');
const files=process.argv.slice(2);let artifacts=[];for(const file of files){const html=fs.readFileSync(file,'utf8');const slides=(html.match(/<section class="slide /g)||[]).length,reveals=(html.match(/ data-step(?:>|\s)/g)||[]).length;ok(slides>0,'has slides');ok(!/<script[^>]+src=|<link[^>]+stylesheet/.test(html),'standalone assets');ok(!/speaker-notes-enc|cmds-deck:|CmdsContent|CmdsDeck/.test(html),'external runtime and encrypted notes excluded');ok(html.includes('data-mode="read"'),'no-JS reading is default');ok((html.match(/class="sheet-footer"/g)||[]).length===slides,'permanent progress footer for every slide');ok((html.match(/class="progress-ticks"/g)||[]).length===slides,'minimal segmented progress retained');ok(html.includes('data:font/woff2;base64,'),'licensed font embedded');artifacts.push({file,slides,reveals});}
console.log(JSON.stringify({status:'pass',checks,artifacts,notReviewed:['browser layout','mobile presentation (capture both modes; run adapters/check_mobile_matrix.js)','actual UI interaction','PDF','physical iPhone','physical keynote screen']}));
